### ISSUE TITLE
Adding an album only adds the tracks that match the album's main artist

### ISSUE THREAD

**Issue by jgillman** [valrus/alfred-mpd#1]
Firstly, `alfred-mpd` is really really really awesome and I'm so glad it exists! Now for it's first bug report 😄 

---

I have an album who's artist is "Mr. Oizo" but some of the tracks in the album have an artist field like "Mr. Oizo feat. Somebody". If I add the album from Alfred only the songs matching the album artist are added.

![image](https://cloud.githubusercontent.com/assets/172217/25409202/044b77ba-29df-11e7-92b6-98e23edaaa2e.png)

# Actual

![image](https://cloud.githubusercontent.com/assets/172217/25409238/29cfdc9c-29df-11e7-850f-a14d8f3ac456.png)

# Expected

![image](https://cloud.githubusercontent.com/assets/172217/25409259/3a1d4224-29df-11e7-879b-fb56808b9d1e.png)

**Comment by valrus** [comment]
Hey, thanks for the report! Always cool to know someone's using your stuff.

This should be fixed in [v1.1.1](https://github.com/valrus/alfred-mpd/releases/tag/v1.1.1). Give it a try?

**Comment by valrus** [comment]
Minor update: that fix caused another small bug, which is fixed in [v1.2.2](https://github.com/valrus/alfred-mpd/releases/tag/v1.2.2).

**Comment by jgillman** [comment]
Fixed! Thank you for your work 😄
